apiVersion: v1
kind: Secret
metadata:
  name: simulator-secret
type: Opaque
stringData:
#  API_URL: http://ingestion-svc.axion.svc.cluster.local:80/api/v1/telemetry/ingest
  API_URL: "http://ingestion-svc.axion-dev.svc.cluster.local:80/api/v1/telemetry/ingest"
  
  # if both ingestion and simulator are in same namespace then use below url
  #API_URL: "http://ingestion-svc:80/api/v1/telemetry/ingest"