apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.serviceName" . }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.postgres.labels.app }}

  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}

  type: {{ .Values.postgres.service.type }}