apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secretName" . }}
  namespace: {{ .Values.namespace }}

type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.database.postgresDb | quote }}

  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.password | quote }}

  