apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: axion

type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: mydb

  PGADMIN_DEFAULT_EMAIL: akkc@gmail.com
  PGADMIN_DEFAULT_PASSWORD: admin123