name: Build & Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write

env:
  DOCKER_IMAGE: amitkkc01/axion-ingestion

jobs:
  build-and-push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./axion-ingestion-service
          file: ./axion-ingestion-service/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Update image tag in Helm values
        run: |
          TAG="${GITHUB_SHA::7}"

          sed -i "s/^  tag:.*/  tag: \"${TAG}\"/" axion-helm-chart/ingestion-service/dev.values.yaml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add axion-helm-chart/ingestion-service/dev.values.yaml
          git commit -m "Update axion-ui image tag to ${TAG}"
          git push